### ISSUE TITLE
inserisci domanda

### ISSUE THREAD

**Issue by manurossi1304** [SoftwareIISGubbio/questionario#11]
dopo aver fatto l'acceso e dopo aver cliccato su "inserisci domanda " mi apre una pagina dove mi dà l'opportunità di inserire una domanda per qualsiasi materia tra quelle elencate ma ,come per la materia, qualsiasi domanda si inserirà non darà alcun tipo di risultato con annesso error 404

**Comment by SoftwareIISGubbio** [comment]
caricato correzioni che potrebbero aver sistemato, per favore controlla di nuovo

**Comment by manurossi1304** [comment]
il bug è stato risolto correttamente
