### ISSUE TITLE
linear gradient diviso

### ISSUE THREAD

**Issue by kikotiro** [SoftwareIISGubbio/questionario#12]
nella pagina "https://github.com/SoftwareIISGubbio/questionario/blob/master/WebContent/utente_form.php" alla riga 11 il linear gradient non si estende a tutta la pagina.

**Comment by kikotiro** [comment]
si può risolvere inserendo "height:100%;" nel css della pagina qui sopra inserita nella riga 11

**Comment by SoftwareIISGubbio** [comment]
rimosso gradiente lineare durante riorganizzazione dei CSS per rendere pagina omogenea con il resto del sito
