### ISSUE TITLE
ritorno alla home dopo aver eseguito un questionario

### ISSUE THREAD

**Issue by manurossi1304** [SoftwareIISGubbio/questionario#13]
dopo aver fatto l'accesso , essere andato su elenco questionario e averne provato a fare uno compare la pagina con il punteggio totalizzato e un pulsante che ti fa ritornare alla home ma se si preme suddetto pulsante la pagina va in error 404

**Comment by SoftwareIISGubbio** [comment]
verifica di nuovo per favore

**Comment by manurossi1304** [comment]
il bug è stato risolto correttamente
