### ISSUE TITLE
Crea Questionario

### ISSUE THREAD

**Issue by GiovanniProcacci** [SoftwareIISGubbio/questionario#15]
Quando si inserisce nel riquadro verde della pagina **questionario_crea_form.php** un nome di un nuovo argomento al clic di "inserisci", aggiunge il questionario alla lista di **questionario_elenco.php** senza impostare un id (imposta 0 come valore) e mette tutti gli argomenti insieme settando i nomi come titolo h1
![Cattur22a](https://user-images.githubusercontent.com/38553502/54186607-0fb38e00-44ac-11e9-9f06-cb8b50505e0f.PNG)

![Cattura](https://user-images.githubusercontent.com/38553502/54186446-b8adb900-44ab-11e9-9afe-85d57f3024a2.PNG)

**Comment by SoftwareIISGubbio** [comment]
abbiamo corretto  i vincoli, verifica di nunovo per favore

**Comment by GiovanniProcacci** [comment]
Si, ora funziona

**Comment by SoftwareIISGubbio** [comment]
grazie per la verifica, chiudo il bug
