### ISSUE TITLE
Inserimento domande- Errore segnalato dal browser 

### ISSUE THREAD

**Issue by GiovanniProcacci** [SoftwareIISGubbio/questionario#19]
Nella pagina "inserimento domande" (**domanda_inserisci_form.php**), dopo la compilazione della domanda e delle risposte al clic del bottone "Inserisci dati", la pagina apre **domanda_inserisci_azione.php** ma non funziona e non salva la domanda con le sue relative risposte. Il browser aprendo le funzioni da programmatore, nello specifico "Console", segnala l'errore:
`  ReferenceError: mysqli_error is not defined[Ulteriori informazioni] domanda_inserisci_azione.php:1:1`.
Con questo post ho voluto segnalare l'errore nello specifico, dato che nell'altra segnalazione presente non c'era scritto.
![1](https://user-images.githubusercontent.com/38553502/54354773-c30cb600-4657-11e9-8c3d-aa34a25d6dbd.PNG)
![2](https://user-images.githubusercontent.com/38553502/54354775-c30cb600-4657-11e9-9c24-89f945a54435.PNG)
![3](https://user-images.githubusercontent.com/38553502/54354776-c30cb600-4657-11e9-96ed-fd3165e58ce0.PNG)
![4](https://user-images.githubusercontent.com/38553502/54354777-c30cb600-4657-11e9-8633-59ac9b1dcc91.PNG)

**Comment by SoftwareIISGubbio** [comment]
Se il bug è già segnalato conviene aggiungere informazioni su quello già presente... se no par contare doppio!
Gli screenshot va bene ma è ppiù comodo da leggere se metti soltanto quelli nencessari
