### ISSUE TITLE
trovare icone

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/questionario#2]
Bisogna trovare un set di icone consistenti, ci sono diversi png ma tutti con stili diversi.
Controllare prima le licenze.

**Comment by Giorgiagrassini** [comment]
Le immagini già presenti bisogna toglierle?

**Comment by SoftwareIISGubbio** [comment]
certamente, fate attenzione ai copyright

**Comment by Giorgiagrassini** [comment]
completato
