### ISSUE TITLE
creazione Questionario, si apre una pagina vuota

### ISSUE THREAD

**Issue by MarkQuinonez** [SoftwareIISGubbio/questionario#22]
quando si preme il pulsante "inserisci", si apre una pagina vuota

**Comment by ErikoBiba1** [comment]
Si apre una pagina vuota solo quando non si inseriscono le domande

By Equestre

**Comment by MarkQuinonez** [comment]
amazing

**Comment by SoftwareIISGubbio** [comment]
duplicato del bug #20 che spiega però cosa succede
in caso questo bug non sia davvero un duplicato per favore riaprilo
