### ISSUE TITLE
problemi con la lettura della pagina  questionario_svolgi_azione

### ISSUE THREAD

**Issue by manurossi1304** [SoftwareIISGubbio/questionario#37]
la pagina questionario_svolgi_azione presenta un problema di data

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in C:\Users\emanuelerossi\Documents\GitHub\questionario\WebContent\questionario_svolgi_azione.php on line 23

**Comment by ErikoBiba1** [comment]
Risolto e spiegato anche come fare a risolvere eventuali errori
