### ISSUE TITLE
bug pagina iniziale

### ISSUE THREAD

**Issue by LeoEquestre** [SoftwareIISGubbio/questionario#4]
nella pagina iniziale si deve togliere il seguente testo: echo ""; echo"";

**Comment by GiovanniProcacci** [comment]
*Nella pagina dopo il login, **index.php**

**Comment by ErikoBiba1** [comment]
nelle ultime 3 righe

**Comment by SoftwareIISGubbio** [comment]
bug corretto, caricamento prossimo commit
