### ISSUE TITLE
inserisci materia

### ISSUE THREAD

**Issue by manurossi1304** [SoftwareIISGubbio/questionario#7]
una volta fatto l'accesso se clicco su inserisci materia  e successivamente provo a cercarla non trova nessuna materia, mi da error 404

**Comment by manurossi1304** [comment]
una volta fatto l' accesso bisogna cliccare su inserisci materia, apparirà una pagina dove potremo inserire una materia qualsiasi ,ma vedremo che non troverà nessuna materia di quelle create nel database

**Comment by SoftwareIISGubbio** [comment]
per favore verifica di nuovo

**Comment by manurossi1304** [comment]
l'errore segnalato in precedenza (error 404) è stato risolto ma una volta inserita la materia e cliccato su "inserisci materia ", compare una pagina completamente bianca

**Comment by SoftwareIISGubbio** [comment]
il bug è stato corretto, l'altro problema sta nel bug #24
