### ISSUE TITLE
Inserimento Domande

### ISSUE THREAD

**Issue by FrancescaPetrini** [SoftwareIISGubbio/questionario#8]
quando si apre inserimento domande e clicchi su inserisci dati ti apre un altra pagina nella quale viene segnalato un errore sull' url

**Comment by SoftwareIISGubbio** [comment]
Abbiamo caricato delle correzioni, per favore controlla di nuovo

**Comment by GiovanniProcacci** [comment]
Nella pagina "inserimento domande" (**domanda_inserisci_form.php**), dopo la compilazione della domanda e delle risposte al clic del bottone "Inserisci dati", la pagina apre domanda_inserisci_azione.php ma non funziona e non salva la domanda con le sue relative risposte. Il browser aprendo le funzioni da programmatore, nello specifico "```
Console", segnala l'errore:
ReferenceError: mysqli_error is not defined[Ulteriori informazioni] domanda_inserisci_azione.php:1:1.
```
Con questo post ho voluto segnalare l'errore nello specifico, dato che nella 
segnalazione presente non c'era scritto.
![1](https://user-images.githubusercontent.com/38553502/54512770-960d1b80-4955-11e9-9122-4451b0e1a993.PNG)
![3](https://user-images.githubusercontent.com/38553502/54512788-9b6a6600-4955-11e9-88f9-cbbfcff955df.PNG)

**Comment by SoftwareIISGubbio** [comment]
Ho appena inserito una domanda e relative risposte e funziona tutto correttamente
