### ISSUE TITLE
URL fisso mi rimanda sempre alla cartella "nicola"

### ISSUE THREAD

**Issue by kikotiro** [SoftwareIISGubbio/questionario#9]
nelle pagine web all'esecuzione di funzioni.l'url viene indirizzato nella cartella nicola creando errori. nella pagina index.php vi è un indirizzo fisso che invia la richiesta a "https://github.com/SoftwareIISGubbio/questionario/blob/master/WebContent/index.php". nella riga 35.

**Comment by SoftwareIISGubbio** [comment]
verifica di nuovo, caricata correzione
